param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\IAR Systems\Embedded Workbench 8322\common\bin\cspybat" -f "E:\t\stp_lib_current\downFromWeb\d0306\MM32SPIN0x_q_Lib_Samples_V1.03_SC\Boards_MM32SPIN0x_q\MM32SPIN0x_q_lib\COMP\COMP_CRV\IAR_PRJ\settings\COMP_CRV.Debug.general.xcl" --backend -f "E:\t\stp_lib_current\downFromWeb\d0306\MM32SPIN0x_q_Lib_Samples_V1.03_SC\Boards_MM32SPIN0x_q\MM32SPIN0x_q_lib\COMP\COMP_CRV\IAR_PRJ\settings\COMP_CRV.Debug.driver.xcl" 
}
else
{
& "C:\IAR Systems\Embedded Workbench 8322\common\bin\cspybat" -f "E:\t\stp_lib_current\downFromWeb\d0306\MM32SPIN0x_q_Lib_Samples_V1.03_SC\Boards_MM32SPIN0x_q\MM32SPIN0x_q_lib\COMP\COMP_CRV\IAR_PRJ\settings\COMP_CRV.Debug.general.xcl" --debug_file=$debugfile --backend -f "E:\t\stp_lib_current\downFromWeb\d0306\MM32SPIN0x_q_Lib_Samples_V1.03_SC\Boards_MM32SPIN0x_q\MM32SPIN0x_q_lib\COMP\COMP_CRV\IAR_PRJ\settings\COMP_CRV.Debug.driver.xcl" 
}
